# Generated by Django 6.0.6 on 2026-06-11 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametroGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        choices=[
                            ("iee", "Impuesto especial de electricidad (tanto por uno)")
                        ],
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=9, max_digits=12)),
                ("vigencia_inicio", models.DateField()),
                ("vigencia_fin", models.DateField(blank=True, null=True)),
                ("fuente", models.CharField(blank=True, max_length=250)),
                ("validado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "parámetro general",
                "verbose_name_plural": "parámetros generales",
                "ordering": ["clave", "-vigencia_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ParametroRegulado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("peaje", "Peaje (CNMC)"),
                            ("cargo", "Cargo (Ministerio)"),
                            ("perdidas", "Coeficiente de pérdidas"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "termino",
                    models.CharField(
                        choices=[
                            ("energia", "Energía (€/kWh)"),
                            ("potencia", "Potencia (€/kW·año)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tarifa",
                    models.CharField(
                        choices=[
                            ("2.0TD", "2.0TD"),
                            ("3.0TD", "3.0TD"),
                            ("6.1TD", "6.1TD"),
                            ("6.2TD", "6.2TD"),
                            ("6.3TD", "6.3TD"),
                            ("6.4TD", "6.4TD"),
                        ],
                        max_length=6,
                    ),
                ),
                ("vigencia_inicio", models.DateField()),
                (
                    "vigencia_fin",
                    models.DateField(
                        blank=True, help_text="Vacío = sigue vigente.", null=True
                    ),
                ),
                ("p1", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("p2", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("p3", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("p4", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("p5", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("p6", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                (
                    "fuente",
                    models.CharField(
                        blank=True,
                        help_text="BOE/Resolución de origen.",
                        max_length=250,
                    ),
                ),
                (
                    "validado",
                    models.BooleanField(
                        default=False, help_text="Revisado por el administrador."
                    ),
                ),
            ],
            options={
                "verbose_name": "parámetro regulado",
                "verbose_name_plural": "parámetros regulados",
                "ordering": ["tarifa", "tipo", "termino", "-vigencia_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                (
                    "cliente_razon_social",
                    models.CharField(max_length=200, verbose_name="razón social"),
                ),
                (
                    "cliente_cif",
                    models.CharField(max_length=20, verbose_name="CIF/NIF"),
                ),
                (
                    "cliente_direccion",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="dirección fiscal"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("presentado", "Presentado"),
                            ("ganado", "Ganado"),
                            ("perdido", "Perdido"),
                        ],
                        default="abierto",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "gestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedientes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gestor",
                    ),
                ),
            ],
            options={
                "verbose_name": "expediente",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comercializadora", models.CharField(max_length=100)),
                (
                    "duracion_meses",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="duración (meses)"
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("fijo", "Precio fijo"), ("indexado", "Indexado")],
                        default="fijo",
                        max_length=10,
                    ),
                ),
                (
                    "gdo",
                    models.BooleanField(
                        default=False, verbose_name="GdO (energía verde)"
                    ),
                ),
                (
                    "fecha_validez",
                    models.DateField(
                        blank=True, null=True, verbose_name="válida hasta"
                    ),
                ),
                (
                    "gestor_nombre",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="gestor comercial"
                    ),
                ),
                (
                    "gestor_telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "gestor_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "atr_energia_incluido",
                    models.BooleanField(
                        default=True,
                        help_text="Si no está incluido, el cálculo suma los peajes y cargos de energía vigentes.",
                        verbose_name="ATR de energía incluido en precios",
                    ),
                ),
                (
                    "atr_potencia_incluido",
                    models.BooleanField(
                        default=False,
                        help_text="Si no, la potencia se factura al ATR regulado vigente (peajes + cargos).",
                        verbose_name="la oferta cotiza precio propio de potencia",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Letra pequeña de la oferta: cierres, condiciones, etc. Se muestra en el comparativo.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="estudios.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "oferta",
                "ordering": ["comercializadora", "duracion_meses"],
            },
        ),
        migrations.CreateModel(
            name="ConceptoAdicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("eur_mwh", "€/MWh sobre consumo"),
                            ("ssaa_umbral", "Regularización SSAA por umbral (€/MWh)"),
                            ("fijo_mes", "€ fijo al mes"),
                            ("pct", "% sobre subtotal (potencia + energía)"),
                        ],
                        default="eur_mwh",
                        max_length=12,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="€/MWh, umbral €/MWh (SSAA), €/mes o % según el tipo elegido.",
                        max_digits=12,
                    ),
                ),
                (
                    "con_perdidas",
                    models.BooleanField(
                        default=False,
                        help_text="Eleva el consumo a barras de central con los coeficientes de pérdidas vigentes.",
                        verbose_name="aplicar pérdidas",
                    ),
                ),
                (
                    "entra_en_iee",
                    models.BooleanField(
                        default=True, verbose_name="forma parte de la base del IEE"
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos",
                        to="estudios.oferta",
                    ),
                ),
            ],
            options={
                "verbose_name": "concepto adicional",
                "verbose_name_plural": "conceptos adicionales",
            },
        ),
        migrations.CreateModel(
            name="PuntoSuministro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titular",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="titular del contrato"
                    ),
                ),
                (
                    "cif_titular",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CIF del titular"
                    ),
                ),
                ("cups", models.CharField(max_length=22, verbose_name="CUPS")),
                (
                    "direccion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="dirección del suministro",
                    ),
                ),
                (
                    "tarifa",
                    models.CharField(
                        choices=[
                            ("2.0TD", "2.0TD"),
                            ("3.0TD", "3.0TD"),
                            ("6.1TD", "6.1TD"),
                            ("6.2TD", "6.2TD"),
                            ("6.3TD", "6.3TD"),
                            ("6.4TD", "6.4TD"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "origen_datos",
                    models.CharField(
                        choices=[
                            ("excel", "Plantilla Excel"),
                            ("api", "API externa"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "potencia_p1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="potencia P1 (kW)",
                    ),
                ),
                (
                    "potencia_p2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="potencia P2 (kW)",
                    ),
                ),
                (
                    "potencia_p3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="potencia P3 (kW)",
                    ),
                ),
                (
                    "potencia_p4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="potencia P4 (kW)",
                    ),
                ),
                (
                    "potencia_p5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="potencia P5 (kW)",
                    ),
                ),
                (
                    "potencia_p6",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="potencia P6 (kW)",
                    ),
                ),
                (
                    "comercializadora_actual",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "modalidad_actual",
                    models.CharField(
                        choices=[("fijo", "Precio fijo"), ("indexado", "Indexado")],
                        default="fijo",
                        max_length=10,
                    ),
                ),
                ("fecha_fin_contrato", models.DateField(blank=True, null=True)),
                (
                    "energia_peajes_incluidos",
                    models.BooleanField(
                        default=True,
                        verbose_name="peajes y cargos incluidos en precio de energía",
                    ),
                ),
                (
                    "precio_energia_p1",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_energia_p2",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_energia_p3",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_energia_p4",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_energia_p5",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_energia_p6",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "potencia_segun_atr",
                    models.BooleanField(
                        default=True, verbose_name="precio de potencia según ATR"
                    ),
                ),
                (
                    "precio_potencia_p1",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_potencia_p2",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_potencia_p3",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_potencia_p4",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_potencia_p5",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "precio_potencia_p6",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos",
                        to="estudios.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "punto de suministro",
                "verbose_name_plural": "puntos de suministro",
            },
        ),
        migrations.CreateModel(
            name="PrecioOferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "energia_p1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P1 (€/kWh)",
                    ),
                ),
                (
                    "energia_p2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P2 (€/kWh)",
                    ),
                ),
                (
                    "energia_p3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P3 (€/kWh)",
                    ),
                ),
                (
                    "energia_p4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P4 (€/kWh)",
                    ),
                ),
                (
                    "energia_p5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P5 (€/kWh)",
                    ),
                ),
                (
                    "energia_p6",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P6 (€/kWh)",
                    ),
                ),
                (
                    "potencia_p1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P1 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P2 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P3 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P4 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P5 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p6",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P6 (€/kW·año)",
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios",
                        to="estudios.oferta",
                    ),
                ),
                (
                    "punto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = aplica a todos los puntos del expediente.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudios.puntosuministro",
                    ),
                ),
            ],
            options={
                "verbose_name": "precios de oferta",
                "verbose_name_plural": "precios de oferta",
            },
        ),
        migrations.CreateModel(
            name="ConsumoMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ]
                    ),
                ),
                (
                    "p1",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="P1 (kWh)",
                    ),
                ),
                (
                    "p2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="P2 (kWh)",
                    ),
                ),
                (
                    "p3",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="P3 (kWh)",
                    ),
                ),
                (
                    "p4",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="P4 (kWh)",
                    ),
                ),
                (
                    "p5",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="P5 (kWh)",
                    ),
                ),
                (
                    "p6",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="P6 (kWh)",
                    ),
                ),
                (
                    "punto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumos",
                        to="estudios.puntosuministro",
                    ),
                ),
            ],
            options={
                "verbose_name": "consumo mensual",
                "verbose_name_plural": "consumos mensuales",
                "ordering": ["anio", "mes"],
            },
        ),
        migrations.CreateModel(
            name="SerieSSAA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ]
                    ),
                ),
                (
                    "valor_real",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="SSAA real (€/MWh)",
                    ),
                ),
                (
                    "valor_considerado",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        verbose_name="SSAA considerado (€/MWh)",
                    ),
                ),
            ],
            options={
                "verbose_name": "SSAA mensual",
                "verbose_name_plural": "serie SSAA mensual",
                "ordering": ["-anio", "-mes"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anio", "mes"), name="unico_ssaa_mes"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="puntosuministro",
            constraint=models.UniqueConstraint(
                fields=("expediente", "cups"), name="unico_cups_por_expediente"
            ),
        ),
        migrations.AddConstraint(
            model_name="preciooferta",
            constraint=models.UniqueConstraint(
                fields=("oferta", "punto"), name="unico_precio_oferta_punto"
            ),
        ),
        migrations.AddConstraint(
            model_name="consumomensual",
            constraint=models.UniqueConstraint(
                fields=("punto", "anio", "mes"), name="unico_mes_por_punto"
            ),
        ),
    ]
