# Generated by Django 6.0.6 on 2026-06-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametroregulado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("peaje", "Peaje (CNMC)"),
                    ("cargo", "Cargo (Ministerio)"),
                    ("perdidas", "Coeficiente de pérdidas (tanto por uno)"),
                    ("imp_local", "Impuesto local (tanto por uno)"),
                ],
                max_length=10,
            ),
        ),
    ]
