# Generated by Django 6.0.6 on 2026-06-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudios", "0002_alter_parametroregulado_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptoadicional",
            name="con_impuesto_local",
            field=models.BooleanField(
                default=False,
                help_text="Multiplica el importe por (1 + impuesto local), p. ej. ×1,015. Lo usan algunas regularizaciones de SSAA.",
                verbose_name="× impuesto local",
            ),
        ),
    ]
