# Generated by Django 6.0.6 on 2026-06-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudios", "0003_conceptoadicional_con_impuesto_local"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="preciooferta",
            name="unico_precio_oferta_punto",
        ),
        migrations.AddField(
            model_name="preciooferta",
            name="tarifa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2.0TD", "2.0TD"),
                    ("3.0TD", "3.0TD"),
                    ("6.1TD", "6.1TD"),
                    ("6.2TD", "6.2TD"),
                    ("6.3TD", "6.3TD"),
                    ("6.4TD", "6.4TD"),
                ],
                default="",
                help_text="Si se indica, aplica a todos los CUPS de esa tarifa del expediente.",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="preciooferta",
            name="punto",
            field=models.ForeignKey(
                blank=True,
                help_text="Si se indica, aplica solo a ese CUPS (tiene prioridad sobre la tarifa).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="estudios.puntosuministro",
            ),
        ),
        migrations.AddConstraint(
            model_name="preciooferta",
            constraint=models.UniqueConstraint(
                fields=("oferta", "tarifa", "punto"), name="unico_precio_oferta_ambito"
            ),
        ),
    ]
