# Generated by Django 6.0.6 on 2026-06-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudios", "0004_remove_preciooferta_unico_precio_oferta_punto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seriessaa",
            options={
                "ordering": ["mes"],
                "verbose_name": "SSAA mensual",
                "verbose_name_plural": "serie SSAA mensual (por mes)",
            },
        ),
        migrations.RemoveConstraint(
            model_name="seriessaa",
            name="unico_ssaa_mes",
        ),
        migrations.AlterField(
            model_name="seriessaa",
            name="mes",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Enero"),
                    (2, "Febrero"),
                    (3, "Marzo"),
                    (4, "Abril"),
                    (5, "Mayo"),
                    (6, "Junio"),
                    (7, "Julio"),
                    (8, "Agosto"),
                    (9, "Septiembre"),
                    (10, "Octubre"),
                    (11, "Noviembre"),
                    (12, "Diciembre"),
                ],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="seriessaa",
            name="valor_considerado",
            field=models.DecimalField(
                decimal_places=3, max_digits=8, verbose_name="SSAA estimado (€/MWh)"
            ),
        ),
        migrations.AlterField(
            model_name="seriessaa",
            name="valor_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
                verbose_name="SSAA real (€/MWh, referencia)",
            ),
        ),
        migrations.RemoveField(
            model_name="seriessaa",
            name="anio",
        ),
    ]
