# Generated by Django 6.0.6 on 2026-06-30 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudios", "0005_alter_seriessaa_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expediente",
            name="oferta_adjudicataria",
            field=models.ForeignKey(
                blank=True,
                help_text="Al cerrar el expediente: oferta aceptada (vacío = sin adjudicación).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="estudios.oferta",
                verbose_name="oferta adjudicataria",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="estado",
            field=models.CharField(
                choices=[("abierto", "Abierto"), ("cerrado", "Cerrado")],
                default="abierto",
                max_length=12,
            ),
        ),
    ]
