# Generated by Django 6.0.6 on 2026-07-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudios", "0007_remapear_estados"),
    ]

    operations = [
        migrations.AddField(
            model_name="oferta",
            name="ssaa_apuntamiento",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Constante multiplicadora (p. ej. 1,02). Vacío = no se aplica (×1).",
                max_digits=6,
                null=True,
                verbose_name="apuntamiento",
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="ssaa_impuesto_municipal",
            field=models.BooleanField(
                default=False,
                help_text="Multiplica la regularización SSAA por (1 + impuesto local), p. ej. ×1,015.",
                verbose_name="aplicar impuesto municipal (Hacienda Local)",
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="ssaa_modo",
            field=models.CharField(
                choices=[
                    ("mensual", "Promedio mensual"),
                    ("horario", "Horario (con profile factors)"),
                ],
                default="mensual",
                help_text="Mensual usa el SSAA del mes; horario lo reparte por periodos con los profile factors.",
                max_length=8,
                verbose_name="modo SSAA",
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="ssaa_perdidas_modo",
            field=models.CharField(
                choices=[
                    ("circular", "Circular CNMC 3/2020 (por periodo)"),
                    ("fija", "Porcentaje fijo (indicar)"),
                ],
                default="circular",
                max_length=8,
                verbose_name="pérdidas en SSAA",
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="ssaa_perdidas_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Solo si las pérdidas son un porcentaje fijo (p. ej. 7 para AT, 17 para BT).",
                max_digits=6,
                null=True,
                verbose_name="pérdidas fijas (%)",
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="ssaa_ref_inferior",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Referencia mínima (solo tipo «con banda»).",
                max_digits=8,
                null=True,
                verbose_name="referencia inferior SSAA (€/MWh)",
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="ssaa_ref_superior",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Techo (tipo «con techo») o referencia máxima (tipo «con banda»).",
                max_digits=8,
                null=True,
                verbose_name="referencia superior SSAA (€/MWh)",
            ),
        ),
        migrations.AddField(
            model_name="oferta",
            name="ssaa_tipo",
            field=models.CharField(
                choices=[
                    ("incluido", "Incluidos en el precio de energía"),
                    ("techo", "Con techo (regulariza por encima)"),
                    ("banda", "Con banda (ref. mínima y máxima)"),
                    ("indexado", "Indexados completos"),
                ],
                default="incluido",
                max_length=10,
                verbose_name="tratamiento SSAA",
            ),
        ),
        migrations.AddField(
            model_name="seriessaa",
            name="anio",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Informativo: de qué año son estos valores (para saber lo actualizados que están).",
                null=True,
                verbose_name="año de referencia",
            ),
        ),
        migrations.AlterField(
            model_name="conceptoadicional",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("eur_mwh", "€/MWh sobre consumo"),
                    ("fijo_mes", "€ fijo al mes"),
                    ("pct", "% sobre subtotal (potencia + energía)"),
                ],
                default="eur_mwh",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="ProfileFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ambito",
                    models.CharField(
                        choices=[
                            ("peninsula_3_6", "Península 3.0TD y 6.xTD"),
                            ("peninsula_20", "Península 2.0TD"),
                            ("canarias", "Canarias"),
                            ("baleares", "Baleares"),
                        ],
                        default="peninsula_3_6",
                        max_length=20,
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ]
                    ),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Informativo: de qué año es este perfil.",
                        null=True,
                        verbose_name="año de referencia",
                    ),
                ),
                (
                    "p1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="P1",
                    ),
                ),
                (
                    "p2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="P2",
                    ),
                ),
                (
                    "p3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="P3",
                    ),
                ),
                (
                    "p4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="P4",
                    ),
                ),
                (
                    "p5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="P5",
                    ),
                ),
                (
                    "p6",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="P6",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile factor mensual",
                "verbose_name_plural": "profile factors (perfiles horarios)",
                "ordering": ["ambito", "mes"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ambito", "mes"), name="unico_profile_ambito_mes"
                    )
                ],
            },
        ),
    ]
