# Generated by Django 6.0.6 on 2026-07-01 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudios", "0009_borrar_conceptos_ssaa_umbral"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfertaCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comercializadora", models.CharField(max_length=100)),
                (
                    "duracion_meses",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="duración (meses)"
                    ),
                ),
                (
                    "gdo",
                    models.BooleanField(
                        default=False, verbose_name="GdO (energía verde)"
                    ),
                ),
                (
                    "atr_energia_incluido",
                    models.BooleanField(
                        default=True,
                        help_text="Si no está incluido, el cálculo suma los peajes y cargos de energía vigentes.",
                        verbose_name="ATR de energía incluido en precios",
                    ),
                ),
                (
                    "atr_potencia_incluido",
                    models.BooleanField(
                        default=False,
                        help_text="Si no, la potencia se factura al ATR regulado vigente (peajes + cargos).",
                        verbose_name="la oferta cotiza precio propio de potencia",
                    ),
                ),
                (
                    "ssaa_tipo",
                    models.CharField(
                        choices=[
                            ("incluido", "Incluidos en el precio de energía"),
                            ("techo", "Con techo (regulariza por encima)"),
                            ("banda", "Con banda (ref. mínima y máxima)"),
                            ("indexado", "Indexados completos"),
                        ],
                        default="incluido",
                        max_length=10,
                        verbose_name="tratamiento SSAA",
                    ),
                ),
                (
                    "ssaa_modo",
                    models.CharField(
                        choices=[
                            ("mensual", "Promedio mensual"),
                            ("horario", "Horario (con profile factors)"),
                        ],
                        default="mensual",
                        help_text="Mensual usa el SSAA del mes; horario lo reparte por periodos con los profile factors.",
                        max_length=8,
                        verbose_name="modo SSAA",
                    ),
                ),
                (
                    "ssaa_ref_superior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Techo (tipo «con techo») o referencia máxima (tipo «con banda»).",
                        max_digits=8,
                        null=True,
                        verbose_name="referencia superior SSAA (€/MWh)",
                    ),
                ),
                (
                    "ssaa_ref_inferior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Referencia mínima (solo tipo «con banda»).",
                        max_digits=8,
                        null=True,
                        verbose_name="referencia inferior SSAA (€/MWh)",
                    ),
                ),
                (
                    "ssaa_perdidas_modo",
                    models.CharField(
                        choices=[
                            ("circular", "Circular CNMC 3/2020 (por periodo)"),
                            ("fija", "Porcentaje fijo (indicar)"),
                        ],
                        default="circular",
                        max_length=8,
                        verbose_name="pérdidas en SSAA",
                    ),
                ),
                (
                    "ssaa_perdidas_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Solo si las pérdidas son un porcentaje fijo (p. ej. 7 para AT, 17 para BT).",
                        max_digits=6,
                        null=True,
                        verbose_name="pérdidas fijas (%)",
                    ),
                ),
                (
                    "ssaa_apuntamiento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Constante multiplicadora (p. ej. 1,02). Vacío = no se aplica (×1).",
                        max_digits=6,
                        null=True,
                        verbose_name="apuntamiento",
                    ),
                ),
                (
                    "ssaa_impuesto_municipal",
                    models.BooleanField(
                        default=False,
                        help_text="Multiplica la regularización SSAA por (1 + impuesto local), p. ej. ×1,015.",
                        verbose_name="aplicar impuesto municipal (Hacienda Local)",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Letra pequeña de la oferta: cierres, condiciones, etc. Se muestra en el comparativo.",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="nombre en el catálogo"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "oferta de catálogo",
                "verbose_name_plural": "ofertas de catálogo",
                "ordering": ["comercializadora", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ConceptoCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("eur_mwh", "€/MWh sobre consumo"),
                            ("fijo_mes", "€ fijo al mes"),
                            ("pct", "% sobre subtotal (potencia + energía)"),
                        ],
                        default="eur_mwh",
                        max_length=12,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="€/MWh, umbral €/MWh (SSAA), €/mes o % según el tipo elegido.",
                        max_digits=12,
                    ),
                ),
                (
                    "con_perdidas",
                    models.BooleanField(
                        default=False,
                        help_text="Eleva el consumo a barras de central con los coeficientes de pérdidas vigentes.",
                        verbose_name="aplicar pérdidas",
                    ),
                ),
                (
                    "con_impuesto_local",
                    models.BooleanField(
                        default=False,
                        help_text="Multiplica el importe por (1 + impuesto local), p. ej. ×1,015. Lo usan algunas regularizaciones de SSAA.",
                        verbose_name="× impuesto local",
                    ),
                ),
                (
                    "entra_en_iee",
                    models.BooleanField(
                        default=True, verbose_name="forma parte de la base del IEE"
                    ),
                ),
                (
                    "oferta_catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos",
                        to="estudios.ofertacatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "concepto de catálogo",
                "verbose_name_plural": "conceptos de catálogo",
            },
        ),
        migrations.CreateModel(
            name="PrecioCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tarifa",
                    models.CharField(
                        choices=[
                            ("2.0TD", "2.0TD"),
                            ("3.0TD", "3.0TD"),
                            ("6.1TD", "6.1TD"),
                            ("6.2TD", "6.2TD"),
                            ("6.3TD", "6.3TD"),
                            ("6.4TD", "6.4TD"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "energia_p1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P1 (€/kWh)",
                    ),
                ),
                (
                    "energia_p2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P2 (€/kWh)",
                    ),
                ),
                (
                    "energia_p3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P3 (€/kWh)",
                    ),
                ),
                (
                    "energia_p4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P4 (€/kWh)",
                    ),
                ),
                (
                    "energia_p5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P5 (€/kWh)",
                    ),
                ),
                (
                    "energia_p6",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="energía P6 (€/kWh)",
                    ),
                ),
                (
                    "potencia_p1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P1 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P2 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P3 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P4 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P5 (€/kW·año)",
                    ),
                ),
                (
                    "potencia_p6",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="potencia P6 (€/kW·año)",
                    ),
                ),
                (
                    "oferta_catalogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios",
                        to="estudios.ofertacatalogo",
                    ),
                ),
            ],
            options={
                "verbose_name": "precios de catálogo",
                "verbose_name_plural": "precios de catálogo",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("oferta_catalogo", "tarifa"),
                        name="unico_precio_catalogo_tarifa",
                    )
                ],
            },
        ),
    ]
