# Generated by Django 6.0.6 on 2026-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudios", "0010_ofertacatalogo_conceptocatalogo_preciocatalogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="expediente",
            name="archivo_original",
            field=models.FileField(
                blank=True,
                help_text="Copia del Excel subido al crear o reimportar el expediente.",
                null=True,
                upload_to="expedientes/",
                verbose_name="archivo Excel original",
            ),
        ),
    ]
